export const keys: string[] = [
  "useClipboard",
  "useChatGPT",
  "usePromiseAll",
  "useHover",
  "useClickOutside",
  "useDebounce",
  "useSort",
  "useMediaQuery",
  "useKeyboardShortcup",
  "useCounter",
  "useLocalStorage",
  "useSearch",
  "useInterval",
  "useScrollIntoView",
];
